services:
  postgres:

    image: postgres:18.6

    ports:
    - "55432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

      TRANSACTION_MIGRATOR_USER: ${TRANSACTION_MIGRATOR_USER}
      TRANSACTION_MIGRATOR_PASSWORD: ${TRANSACTION_MIGRATOR_PASSWORD}
      TRANSACTION_APP_USER: ${TRANSACTION_APP_USER}
      TRANSACTION_APP_PASSWORD: ${TRANSACTION_APP_PASSWORD}

      RISK_MIGRATOR_USER: ${RISK_MIGRATOR_USER}
      RISK_MIGRATOR_PASSWORD: ${RISK_MIGRATOR_PASSWORD}
      RISK_APP_USER: ${RISK_APP_USER}
      RISK_APP_PASSWORD: ${RISK_APP_PASSWORD}

      AUDIT_MIGRATOR_USER: ${AUDIT_MIGRATOR_USER}
      AUDIT_MIGRATOR_PASSWORD: ${AUDIT_MIGRATOR_PASSWORD}
      AUDIT_APP_USER: ${AUDIT_APP_USER}
      AUDIT_APP_PASSWORD: ${AUDIT_APP_PASSWORD}

      NOTIFICATION_MIGRATOR_USER: ${NOTIFICATION_MIGRATOR_USER}
      NOTIFICATION_MIGRATOR_PASSWORD: ${NOTIFICATION_MIGRATOR_PASSWORD}
      NOTIFICATION_APP_USER: ${NOTIFICATION_APP_USER}
      NOTIFICATION_APP_PASSWORD: ${NOTIFICATION_APP_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgres:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: