spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:55432/transaction_db
    username: ${TRANSACTION_APP_USER}
    password: ${TRANSACTION_APP_PASSWORD}

  flyway:
    url: ${TRANSACTION_DB_URL:jdbc:postgresql://localhost:55432/transaction_db}
    user: ${TRANSACTION_MIGRATOR_USER}
    password: ${TRANSACTION_MIGRATOR_PASSWORD}
    schemas: flyway
    default-schema: flyway
    create-schemas: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoint:
    health:
      show-details: always